In [1]:
import numpy as np

    # 23

In [10]:
array = np.random.randint(0, 10, size=(2,4)).astype(np.int16)

In [11]:
array

array([[1, 7, 4, 6],
       [3, 0, 4, 6]], dtype=int16)

In [12]:
type(array)

numpy.ndarray

In [13]:
array.dtype

dtype('int16')

    # 9 Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) hint: reshape

In [15]:
np.random.randint(0,9, (3,3))

array([[5, 0, 2],
       [4, 0, 6],
       [0, 6, 4]])

In [19]:
np.random.randint(0,9,9).reshape((3,3))

array([[0, 7, 6],
       [8, 5, 1],
       [6, 6, 6]])

    # 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
hint: https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.unravel_index.html

In [21]:
n_array = np.random.randint(0,10,(6,7,8))

In [29]:
n_array.reshape((6*7*8,))[100]

0

In [27]:
np.unravel_index([100], (6,7,8))

(array([1]), array([5]), array([4]))

In [28]:
n_array[1][5][4]

0